/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package idss;

import java.awt.Graphics;

/**
 *
 * @author Andrew
 */
public class MapPanel extends javax.swing.JPanel {
    
    MapInfo map;
        
    /**
     * Creates new form MapPanel
     */
    public MapPanel() {
        initComponents();
    }

    public void setMapInfo(MapInfo map) {
        this.map = map;
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        if (map != null) {
            for (Point p : map.points) {
                p.drawTo(g, 0, 0);
            }
            for (Road r : map.roads) {
                r.drawTo(g, 0, 0);
            }
        }

        //g.drawString("BLAH", 20, 20);
        g.drawRect(0, 0, getWidth()-1, getHeight()-1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
